apiVersion: v1
kind: Service
metadata:
  name: motd-service
spec:
  selector:
    app: motd
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motd
spec:
  selector:
    matchLabels:
      app: motd
  replicas: 3
  template:
    metadata:
      labels:
        app: motd
    spec:
      containers:
      - name: motd
        image: motd:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080